### PR TITLE
Updates to backup.xsf / Ignore the rest.

### PR DESCRIPTION
**Pull request by seurat-atreides**
Please review the corrections I have made to backup.xsf.
I have tested the script for correct functioning on X440G2 and X460G2 fw ver. 21.1.3.

### CODE REVIEW

**Comment by stewilliams-extr** [comment]
We can't accept this pull request, as it is deleting the Netsight folder.  Could you resubmit the pull request with just the two files changed, or we can update the script.

**Comment by seurat-atreides** [comment]
Closing this pull request since it's not correctly synchronized with the origin.

**Comment by seurat-atreides** [comment]
I'm working on getting my fork synchronized before I submit a new pull request.

**Comment by seurat-atreides** [comment]
I apologize for the bad, I'm very new to GIT/GITHUB and thought you
could cherry-pick the file y edited.
I will resync my fork and resubmit the pull request.

**Comment by stewilliams-extr** [comment]
You can cherry pick the commits, and I was going to do that.  Thanks for correcting the script!

**Pull request closed without merging**
