### PR TITLE
Add WiNG TFTP support

### PR DESCRIPTION
**Pull request by tknv**
Tested at XMC 8.1.3.65 with RFS6K 5.9.1.4

### CODE REVIEW

**Comment by tknv** [comment]
At Operation log: success, but cannot find it under tftpboot/. closing due to need more test

**Comment by tknv** [comment]
I think it looks ok.

```
root@xmc:~# ls -la /usr/local/Extreme_Networks/NetSight/appdata/InventoryMgr/configs/3/1532486169116
total 56
drwxr-xr-x  2 root root  4096 Jul 25 10:36 .
drwxr-xr-x 34 root root  4096 Jul 25 10:36 ..
-rw-r--r--  1 root root 49012 Jul 25 10:36 172_16_20_1.cfg

```
and 
```
407216	1532485701762	Inventory Server.6.Event	root	172.16.10.93	172.16.20.1	Archive Save	Archive Save Management Center Archive: (172.16.20.1) Version Stamp: Jul 25, 2018 10:27:47 AM - Configuration Retrieved -- Config saved on 07/25/2018 10:27:47 AM for device 172.16.20.1 : Configuration Retrieved -- Config saved on 07/25/2018 10:27:47 AM for device 172.16.20.1		
419221	1532486204264	Inventory Server.6.Event	root	172.16.10.93	172.16.20.1	Archive Save	Archive Save Management Center Archive: (172.16.20.1) Version Stamp: Jul 25, 2018 10:36:09 AM - Configurations Are Equal -- [Config saved on 07/25/2018 10:36:09 AM for device 172.16.20.1] and [Config saved on 07/25/2018 10:27:47 AM for device 172.16.20.1] : Configurations Are Equal -- [Config saved on 07/25/2018 10:36:09 AM for device 172.16.20.1] and [Config saved on 07/25/2018 10:27:47 AM for device 172.16.20.1]	
```

**Comment by stewilliams-extr** [comment]
There is one already built into newer versions of Netsight.  If you want you can put the below official script in, but make sure you update the main readme.md file to include the name and description as we do in this readme.

https://github.com/extremenetworks/ExtremeScripting/blob/master/Netsight/cfg_backup_scripts/README.md

```
--- Use these scripts to manage Motorola Wireless devices
name="Motorola Wireless - TFTP"
desc="Motorola Wireless SSH/TFTP Scripts"
protocol=TFTP
separator=/
timed_reset_delay_format="HH:mm:ss:SS"
-----BEGIN SCRIPT "Configuration Upload"-----
enable
copy startup-config %TFTP_URL%
@receive 20
exit
-----END SCRIPT-----
-----BEGIN SUCCESS "Configuration Upload"-----
-----END SUCCESS-----
```

**Comment by ZdenekPala** [comment]
Can you please explain why you do not use the build-in script in 8.1.3.65? if it does not work then it should be handled by GTAC. if your script is "better" we can handle it as feature enhancement.

My suggestion here is to either:
1. not merge and leave without change
2. merge with updating the README.md to state there is already supported script build-in
3. take the official and publish here = this can be tricky due to legal compliance

**Comment by tknv** [comment]
@ZdenekPala I see, because by default XMC did not pull config from WiNG. ThenI did not see select list well and simply wrote it. But now found it "Motorola Wireless - TFTP" in select list. Also, able to obtain config file from WiNG. 
Thanks. I will close this PR.

**Pull request closed without merging**
